parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony
    database_user: root
    database_password: ~
    mailer_transport: gmail
    mailer_encryption: ssl
    mailer_auth_mode: login
    mailer_host: smtp.gmail.com
    mailer_user: talsquin
    mailer_password: pipipichu
    locale: en
    secret: 5f0a26624565725ef8bab0af85da812a7e1a2493
    database_path: null
